### ISSUE TITLE
[Feature Request] Support Multi Dimension Array Query Params

### ISSUE THREAD

**Issue by yoelpc4** [reststate/reststate-client#148]
Currently this package only supports single dimension array filter query params.
https://github.com/reststate/reststate-client/blob/2b01b1282a3c2e14916f05c428f1e793c176fb4b/src/Resource.js#L1-L5

Can you adding an enhancement to supporting multi dimension array query params e.g: `?filter[period][start_date]=2020-01-01&filter[period][end_date]=2020-01-31` for the sake of API filter flexibility?

**Comment by yoelpc4** [comment]
If you think this is not necessary no problem, I can solved this using comma notation `?filter[period]=2020-01-01,2020-01-31`

**Comment by CodingItWrong** [comment]
Thanks for reporting this need.

Yes, I'd like to support this use case. I checked the JSON:API spec, and it looks like the spec makes no assumptions about how you might use the `filter` query parameter; either the single-level square brackets like I was doing, or the multi-level square brackets you are. I might just make the filtering more flexible so that you can pass in in any arguments you like, regardless of plan or scheme.

I am wrapping up another project in the next few days, then i should hopefully be able to look into this.

**Comment by CodingItWrong** [comment]
@yoelpc4 Let me know what you think of this solution: https://github.com/reststate/reststate-client/pull/151

**Comment by yoelpc4** [comment]
Do you have released that solution?

**Comment by CodingItWrong** [comment]
@yoelpc4 No, first please review #151 to see if the way it's used is satisfactory for your use case. If it is, I'll release it and then you can give it a try. You could pull down the branch for #151 to try it locally, but that can be tricky to do, so don't feel the need to do that.

**Comment by CodingItWrong** [comment]
Closed for no response. Please feel free to reply to the above question to reopen
